# Generated by Django 3.0.6 on 2020-05-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='v1.Book'),
        ),
    ]
